### ISSUE TITLE
MVP Issues VNG Realisatie huwelijksplanner

### ISSUE THREAD

**Issue by savitris** [frameless/utrecht-huwelijksplanner#324]
# Algemeen MVP

[TODO lijst VNG realisatie huwelijksplanner](https://github.com/VNG-Realisatie/huwelijksplanner/projects/5#column-7780299)

## Toepasselijke Issues

- [ ] [Dagen en tijdstippen waarop gereserveerd kan worden instellen. #692](https://github.com/VNG-Realisatie/huwelijksplanner/issues/692)
- [ ] [Dat de inwoner kiest voor een plechtigheid: partnerschap of huwelijk. #670](https://github.com/VNG-Realisatie/huwelijksplanner/issues/670)
- [ ] [Dat de inwoner kiest voor een ceremonie (flits, eenvoudig of gratis). #675](https://github.com/VNG-Realisatie/huwelijksplanner/issues/675)
- [ ] [Dat de inwoner kiest voor een datum. #683](https://github.com/VNG-Realisatie/huwelijksplanner/issues/683)
- [ ] [Dat de inwoner kiest voor extra's: blauw en rood trouwboekje. #684](https://github.com/VNG-Realisatie/huwelijksplanner/issues/684)
- [ ] [Dat de inwoner nodigt getuigen uit en geeft deze door. #685](https://github.com/VNG-Realisatie/huwelijksplanner/issues/685)
- [ ] [De inwoner kan een partner aangeven en uitnodigen. #686](https://github.com/VNG-Realisatie/huwelijksplanner/issues/686)
- [ ] [Partner en getuigen moeten instemming kunnen geven. #687](https://github.com/VNG-Realisatie/huwelijksplanner/issues/687)
- [ ] [Er wordt betaald via ideal. #688](https://github.com/VNG-Realisatie/huwelijksplanner/issues/688)
- [ ] [De standaard locatie wordt automatisch toegewezen. #689](https://github.com/VNG-Realisatie/huwelijksplanner/issues/689)
- [ ] [Na indienen (en betalen = indienen) kan een reservering niet meer door een burger gewijzigd worden. De burger moet contact opnemen met de gemeente. #682](https://github.com/VNG-Realisatie/huwelijksplanner/issues/682)
- [ ] [Wijzigen kan tot een reservering/verzoek is ingediend #680](https://github.com/VNG-Realisatie/huwelijksplanner/issues/680)
- [ ] [Bevestiging ontvangen van alles wat je indient. #681](https://github.com/VNG-Realisatie/huwelijksplanner/issues/681)
- [ ] [Naamgebruik aan kunnen geven in de huwelijksplanner. #676](https://github.com/VNG-Realisatie/huwelijksplanner/issues/676)
- [ ] [Een burger moet een huwelijk kunnen annuleren. #673](https://github.com/VNG-Realisatie/huwelijksplanner/issues/673)
- [ ] [Een medewerker moet een huwelijk kunnen annuleren. #672](https://github.com/VNG-Realisatie/huwelijksplanner/issues/672)
- [ ] [Een medewerker moet kunnen zien welke huwelijken geannuleerd zijn. #671](https://github.com/VNG-Realisatie/huwelijksplanner/issues/671)

## Niet Toepasselijke Issues

- [ ] [For the employee, this means that the complete request must be transparent and adjustable in the dashboard. #691](https://github.com/VNG-Realisatie/huwelijksplanner/issues/691)
- [ ] [De Babs wordt handmatig toegewezen door een medewerker. #690](https://github.com/VNG-Realisatie/huwelijksplanner/issues/690)
- [ ] [Een niet ingediend verzoek wordt na reeds afgesproken termijn (zie userstory X) verwijderd. #679](https://github.com/VNG-Realisatie/huwelijksplanner/issues/679)
- [ ] [De inwoner kan een melding voorgenomen huwelijk indienen #678](https://github.com/VNG-Realisatie/huwelijksplanner/issues/678)
- [ ] [De medewerker kan een melding voorgenomen huwelijk afhandelen. #677](https://github.com/VNG-Realisatie/huwelijksplanner/issues/677)
- [ ] [Afhandelen van naamgebruik door medewerker: aan de hand van inschatting van het werk. Later te bepalen. #674](https://github.com/VNG-Realisatie/huwelijksplanner/issues/674)
